# Generated by Django 5.0.6 on 2024-06-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'ORDER_PROCESSED'), (3, 'ORDER_DELIVERED'), (4, 'ORDER_REJECTED'), (1, 'ORDER_CONFIRMED'), (0, 'CART_STAGE')], default=0),
        ),
    ]
