# Generated by Django 5.0.6 on 2024-06-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_deliveryaddress_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
